# Smoke test of HSQ quantizer.

In [18]:
import hierarchical_binary_quantization.hbq as hbq
import torch
batches, vector_lenght = 3,8
z = torch.rand(batches,vector_lenght) * 2 - 1
z

tensor([[-0.7021, -0.2312, -0.2543,  0.6547,  0.9693, -0.0330, -0.0820,  0.5468],
        [-0.6252,  0.4240,  0.8624, -0.2712,  0.3147,  0.7736,  0.7267,  0.9978],
        [-0.2858,  0.3803,  0.8039, -0.7658,  0.0067, -0.2840, -0.4210, -0.5586]])

In [19]:
hbq.hbq(z,n_rounds=1)

(tensor([[-0.5000, -0.5000, -0.5000,  0.5000,  0.5000, -0.5000, -0.5000,  0.5000],
         [-0.5000,  0.5000,  0.5000, -0.5000,  0.5000,  0.5000,  0.5000,  0.5000],
         [-0.5000,  0.5000,  0.5000, -0.5000,  0.5000, -0.5000, -0.5000, -0.5000]]),
 tensor([[0, 0, 0, 1, 1, 0, 0, 1],
         [0, 1, 1, 0, 1, 1, 1, 1],
         [0, 1, 1, 0, 1, 0, 0, 0]], dtype=torch.int32))

In [20]:
z = torch.rand(batches,16 * 16 * 3) * 2 - 1
hbq.hbq(z,n_rounds=2)

(tensor([[ 0.2500, -0.2500, -0.7500,  ...,  0.7500,  0.2500, -0.7500],
         [-0.7500, -0.7500, -0.2500,  ...,  0.7500, -0.7500, -0.2500],
         [ 0.7500, -0.7500,  0.2500,  ..., -0.7500,  0.7500,  0.2500]]),
 tensor([[2, 1, 0,  ..., 3, 2, 0],
         [0, 0, 1,  ..., 3, 0, 1],
         [3, 0, 2,  ..., 0, 3, 2]], dtype=torch.int32))

In [43]:

x = torch.tensor([[-1.5, -0.5, 0.5, 1.5]], requires_grad=True)

quantizer = hbq.HBQQuantizer(n_rounds=2)
q_out, tokenids = quantizer(x)

loss = (q_out ** 2).sum()

# 4. Compute gradients
loss.backward()

# 5. Print results to verify
print("=== Validation Results ===")
print(f"Original Input x:         {x.data}")
print(f"Quantized Output q_out:  {q_out.data}")
print(f"Token IDs q_out:  {tokenids.data}")
print(f"Do gradients exist?      {x.grad is not None}")
print(f"Computed Gradients x.grad: {x.grad}")

=== Validation Results ===
Original Input x:         tensor([[-1.5000, -0.5000,  0.5000,  1.5000]])
Quantized Output q_out:  tensor([[-0.7500, -0.2500,  0.2500,  0.7500]])
Token IDs q_out:  tensor([[0, 1, 2, 3]], dtype=torch.int32)
Do gradients exist?      True
Computed Gradients x.grad: tensor([[-0.2711, -0.3932,  0.3932,  0.2711]])


In [47]:
hbq_module = hbq.HBQQuantizer(1)
z = torch.rand(batches,3, 16, 16,requires_grad=True) * 2 - 1

q_out, indicies = hbq_module.forward(z)
q_out.shape, indicies.shape

(torch.Size([3, 3, 16, 16]), torch.Size([3, 3, 16, 16]))

In [36]:
loss = (q_out ** 2).sum()
loss.backward()


In [ ]:

x = torch.tensor([-1.5, -0.5, 0.5, 1.5], requires_grad=True)

# 2. Pass input through your custom module
quantizer = hbq.HBQQuantizer(n_rounds=3)
q_out, tokenids = quantizer(x)

# 3. Define a mock loss function (e.g., Mean Squared Error style)
loss = (q_out ** 2).sum()

# 4. Compute gradients
loss.backward()

# 5. Print results to verify
print("=== Validation Results ===")
print(f"Original Input x:         {x.data}")
print(f"Quantized Output q_out:  {q_out.data}")
print(f"Do gradients exist?      {x.grad is not None}")
print(f"Computed Gradients x.grad: {x.grad}")

=== Validation Results ===
Original Input x:         tensor([-1.5000, -0.5000,  0.5000,  1.5000])
Quantized Output q_out:  tensor([-0.8750, -0.3750,  0.3750,  0.8750])
Do gradients exist?      True
Computed Gradients x.grad: tensor([-0.3162, -0.5898,  0.5898,  0.3162])
