# Smoke test of the HBQ quantizer.

In [1]:
import hierarchical_binary_quantization.hbq as hbq
import torch

## Verify that with 2 rounds of quantization, 

* There are 4 possible values (2 bits) for each element of the latent embedding vectors
* They can be represented by a 2-bit number (0 through 3) that fits comfortably in an int8

In [12]:
torch.manual_seed(42)
batches, vector_lenght = 3,8
z = torch.randn(batches,vector_lenght)
print(z)
hbq.hbq(z,n_rounds=2)

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [ 0.3559, -0.6866, -0.4934,  0.2415, -1.1109,  0.0915, -2.3169, -0.2168],
        [-0.3097, -0.3957,  0.8034, -0.6216, -0.5920, -0.0631, -0.8286,  0.3309]])


(tensor([[ 0.7500,  0.7500,  0.7500, -0.7500,  0.7500, -0.7500, -0.2500, -0.7500],
         [ 0.2500, -0.7500, -0.2500,  0.2500, -0.7500,  0.2500, -0.7500, -0.2500],
         [-0.2500, -0.2500,  0.7500, -0.7500, -0.7500, -0.2500, -0.7500,  0.2500]]),
 tensor([[3, 3, 3, 0, 3, 0, 1, 0],
         [2, 0, 1, 2, 0, 2, 0, 1],
         [1, 1, 3, 0, 0, 1, 0, 2]], dtype=torch.int8))

## Verify that gradient exist and flow through the HBQQuantizer(torch.nn.Module)

In [4]:
img = [[[-0.7,-0.2],[0.2,0.7]]]
x = torch.tensor([img], requires_grad=True)
quantizer = hbq.HBQQuantizer(n_rounds=2)
q_out, aux = quantizer(x)
loss = (q_out ** 2).sum()
# 4. Compute gradients
loss.backward()
# 5. Print results to verify
print("=== Validation Results ===")
print(f"Original Input x:         {x}")
print(f"Quantized Output q_out:  {q_out}")
print(f"bit_codes:  {aux.bit_codes}")
print(f"Token IDs q_out:  {aux.tokens}")
print(f"Do gradients exist?      {x.grad is not None}")
print(f"Computed Gradients x.grad: {x.grad}")

=== Validation Results ===
Original Input x:         tensor([[[[-0.7000, -0.2000],
          [ 0.2000,  0.7000]]]], requires_grad=True)
Quantized Output q_out:  tensor([[[[-0.7500, -0.2500],
          [ 0.2500,  0.7500]]]], grad_fn=<AddBackward0>)
bit_codes:  tensor([[[[0, 1],
          [2, 3]]]], dtype=torch.int8)
Token IDs q_out:  tensor([[[0, 1],
         [2, 3]]])
Do gradients exist?      True
Computed Gradients x.grad: tensor([[[[-1.5000, -0.5000],
          [ 0.5000,  1.5000]]]])


## Demonstrate that the token component collapses multiple channels into a signle token.

In this case, 5 batches, 3 channels, H=8, W=8, gets quantized into 2 bits per channel, and the 

In [5]:
z = torch.randn(2,3,4,4)
quantizer = hbq.HBQQuantizer(n_rounds=2)
quantized_latents, q_aux = quantizer(z)
q_aux.tokens.shape
q_aux.tokens

tensor([[[34, 34, 47, 24],
         [43, 11, 44, 53],
         [48, 47, 18, 47],
         [15, 61,  4, 48]],

        [[51, 12, 56, 23],
         [54, 44,  1, 26],
         [ 1, 59, 27, 30],
         [39,  8, 62, 47]]])

In [6]:
hbq.tokens_to_bit_codes(torch.tensor([228]),latent_dim=x.shape[-1],n_rounds=2)

tensor([[0, 1]])

In [7]:
hbq.bit_codes_to_quantized_latent(q_aux.bit_codes,n_rounds=2)

tensor([[[[ 0.2500,  0.2500,  0.7500, -0.7500],
          [ 0.7500,  0.7500, -0.7500, -0.2500],
          [-0.7500,  0.7500,  0.2500,  0.7500],
          [ 0.7500, -0.2500, -0.7500, -0.7500]],

         [[-0.7500, -0.7500,  0.7500,  0.2500],
          [ 0.2500,  0.2500,  0.7500, -0.2500],
          [-0.7500,  0.7500, -0.7500,  0.7500],
          [ 0.7500,  0.7500, -0.2500, -0.7500]],

         [[ 0.2500,  0.2500,  0.2500, -0.2500],
          [ 0.2500, -0.7500,  0.2500,  0.7500],
          [ 0.7500,  0.2500, -0.2500,  0.2500],
          [-0.7500,  0.7500, -0.7500,  0.7500]]],


        [[[ 0.7500, -0.7500, -0.7500,  0.7500],
          [ 0.2500, -0.7500, -0.2500,  0.2500],
          [-0.2500,  0.7500,  0.7500,  0.2500],
          [ 0.7500, -0.7500,  0.2500,  0.7500]],

         [[-0.7500,  0.7500,  0.2500, -0.2500],
          [-0.2500,  0.7500, -0.7500,  0.2500],
          [-0.7500,  0.2500,  0.2500,  0.7500],
          [-0.2500,  0.2500,  0.7500,  0.7500]],

         [[ 0.7500, -0.7500,