# Smoke test of HSQ quantizer.

In [1]:
import hierarchical_binary_quantization.hbq as hbq
import torch
batches, vector_lenght = 3,8
z = torch.rand(batches,vector_lenght) * 2 - 1

In [2]:
hbq.hbq(z,n_rounds=2)

(tensor([[ 0.7500,  0.7500, -0.7500, -0.7500, -0.7500, -0.2500,  0.2500,  0.2500],
         [-0.2500,  0.7500, -0.2500, -0.2500,  0.7500, -0.2500,  0.2500, -0.2500],
         [ 0.2500,  0.2500,  0.7500,  0.2500,  0.2500,  0.7500,  0.7500,  0.7500]]),
 tensor([[3, 3, 0, 0, 0, 1, 2, 2],
         [1, 3, 1, 1, 3, 1, 2, 1],
         [2, 2, 3, 2, 2, 3, 3, 3]]))

In [22]:
img = [[[-0.7,-0.2],[0.2,0.7]]]
x = torch.tensor([img], requires_grad=True)
quantizer = hbq.HBQQuantizer(n_rounds=2)
q_out, aux = quantizer(x)
loss = (q_out ** 2).sum()
# 4. Compute gradients
loss.backward()
# 5. Print results to verify
print("=== Validation Results ===")
print(f"Original Input x:         {x}")
print(f"Quantized Output q_out:  {q_out}")
print(f"bit_codes:  {aux.bit_codes}")
print(f"Token IDs q_out:  {aux.tokens}")
print(f"Do gradients exist?      {x.grad is not None}")
print(f"Computed Gradients x.grad: {x.grad}")

=== Validation Results ===
Original Input x:         tensor([[[[-0.7000, -0.2000],
          [ 0.2000,  0.7000]]]], requires_grad=True)
Quantized Output q_out:  tensor([[[[-0.7500, -0.2500],
          [ 0.2500,  0.7500]]]], grad_fn=<AddBackward0>)
bit_codes:  tensor([[[[0, 1],
          [2, 3]]]])
Token IDs q_out:  tensor([[[0, 1],
         [2, 3]]])
Do gradients exist?      True
Computed Gradients x.grad: tensor([[[[-0.9521, -0.4805],
          [ 0.4805,  0.9521]]]])


In [4]:
z = torch.rand(5,3,8,8)
quantizer = hbq.HBQQuantizer(n_rounds=2)
quantizer(z)

(tensor([[[[0.7500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500, 0.2500, 0.2500],
           [0.2500, 0.2500, 0.2500, 0.7500, 0.7500, 0.2500, 0.7500, 0.2500],
           [0.7500, 0.7500, 0.2500, 0.2500, 0.7500, 0.7500, 0.7500, 0.7500],
           [0.7500, 0.7500, 0.7500, 0.2500, 0.2500, 0.2500, 0.2500, 0.7500],
           [0.7500, 0.2500, 0.7500, 0.7500, 0.2500, 0.7500, 0.7500, 0.2500],
           [0.7500, 0.2500, 0.7500, 0.7500, 0.2500, 0.7500, 0.2500, 0.2500],
           [0.2500, 0.2500, 0.7500, 0.7500, 0.2500, 0.2500, 0.2500, 0.2500],
           [0.7500, 0.2500, 0.7500, 0.7500, 0.2500, 0.7500, 0.2500, 0.7500]],
 
          [[0.7500, 0.7500, 0.7500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500],
           [0.7500, 0.2500, 0.7500, 0.2500, 0.7500, 0.2500, 0.2500, 0.2500],
           [0.2500, 0.2500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500],
           [0.7500, 0.7500, 0.7500, 0.7500, 0.2500, 0.2500, 0.2500, 0.2500],
           [0.7500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.7500, 0.750

In [5]:
hbq.tokens_to_bit_codes(torch.tensor([228]),latent_dim=x.shape[-1],n_rounds=2)

tensor([[0, 1, 2, 3, 0, 0, 0, 0]])

In [6]:
hbq.bit_codes_to_quantized_latent(aux.bit_codes,n_rounds=2)

tensor([[[[0.2500, 0.2500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500],
          [0.7500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.7500, 0.2500],
          [0.2500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500, 0.7500],
          [0.2500, 0.7500, 0.7500, 0.7500, 0.2500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.7500, 0.2500, 0.7500, 0.2500, 0.7500],
          [0.7500, 0.7500, 0.7500, 0.7500, 0.2500, 0.7500, 0.2500, 0.2500],
          [0.2500, 0.7500, 0.2500, 0.2500, 0.2500, 0.7500, 0.7500, 0.2500],
          [0.7500, 0.2500, 0.7500, 0.7500, 0.2500, 0.2500, 0.2500, 0.2500]],

         [[0.2500, 0.2500, 0.7500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500],
          [0.2500, 0.7500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500, 0.2500],
          [0.7500, 0.2500, 0.7500, 0.2500, 0.7500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.2500, 0.7500, 0.2500, 0.7500, 0.7500],
          [0.2500, 0.7500, 0.2500, 0.2500, 0.7500, 0.2500, 0.2500, 0.7500],
          